version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_HOST: mysql
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.php-fpm71
    volumes:
      - "..:/var/www/html/training"
      - "./resources/php.ini:/usr/local/etc/php/php.ini:ro"
    depends_on:
      - mysql
    expose: 
      - "9000"
  front:
    image: nginx
    ports:
      - 8083:80
    depends_on:
      - php
    volumes:
      - "..:/var/www/html/training:ro"
      - "./front/default.conf:/etc/nginx/conf.d/default.conf:ro"
    working_dir: "/var/www/html/training"
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
